apiVersion: v2
appVersion: "25.08"
dependencies:
- name: postgresql
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 16.2.4
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: A Helm chart for NeMo Auditor service
home: https://nvidia.com
maintainers:
- name: NVIDIA, Inc.
  url: https://www.nvidia.com
name: nemo-auditor
type: application
version: 25.8.0
