apiVersion: v2
appVersion: "25.08"
dependencies:
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
- condition: postgresql.enabled
  name: postgresql
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 14.0.4
- condition: milvus.enabled
  name: milvus
  repository: https://zilliztech.github.io/milvus-helm
  version: 4.1.26
- condition: zipkin.enabled
  name: zipkin
  repository: https://zipkin.io/zipkin-helm
  version: 0.1.2
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.78.1
description: NeMo Evaluator Microservice Helm Chart
name: nemo-evaluator
type: application
version: 25.8.0
