apiVersion: v2
appVersion: "25.08"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://dockerhub.nvidia.com/bitnamicharts
  version: 13.3.1
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: NeMo Entity Store Microservice Helm Chart
home: https://nvidia.com
maintainers:
- name: NVIDIA, Inc.
  url: https://www.nvidia.com
name: nemo-entity-store
type: application
version: 25.8.0
